# Generated by Django 6.0 on 2025-12-10 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        help_text="ID de l'utilisateur (référence à la table users)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Panier",
                "verbose_name_plural": "Paniers",
                "db_table": "carts",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id",), name="unique_active_cart_per_user"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.IntegerField(
                        help_text="ID du produit (référence à la table products)"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantité (unités ou kg selon le type de vente)",
                        max_digits=10,
                    ),
                ),
                (
                    "price_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix unitaire au moment de l'ajout au panier",
                        max_digits=10,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.cart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item du panier",
                "verbose_name_plural": "Items du panier",
                "db_table": "cart_items",
                "indexes": [
                    models.Index(
                        fields=["cart", "product_id"],
                        name="cart_items_cart_id_421c1e_idx",
                    ),
                    models.Index(
                        fields=["product_id"], name="cart_items_product_6a1de7_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cart", "product_id"), name="unique_product_per_cart"
                    )
                ],
            },
        ),
    ]
