# Generated by Django 6.0 on 2025-12-10 05:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.IntegerField(
                        help_text="ID du client (référence à la table users)"
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        editable=False,
                        help_text="Numéro unique de commande (ex: DZF-20231215-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("preparing", "En préparation"),
                            ("ready", "Prête"),
                            ("completed", "Terminée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("pickup_producer", "Retrait chez producteur"),
                            ("pickup_point", "Retrait en point de collecte"),
                        ],
                        default="pickup_producer",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(
                        blank=True,
                        help_text="Adresse de livraison ou point de collecte",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Instructions spéciales du client",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
                "db_table": "orders",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client_id", "-created_at"],
                        name="orders_client__80fbb4_idx",
                    ),
                    models.Index(
                        fields=["order_number"], name="orders_order_n_1336be_idx"
                    ),
                    models.Index(fields=["status"], name="orders_status_762191_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "producer_id",
                    models.IntegerField(
                        help_text="ID du producteur (référence à la table producers)"
                    ),
                ),
                (
                    "sub_order_number",
                    models.CharField(
                        editable=False,
                        help_text="Numéro de sous-commande (ex: DZF-20231215-001-P1)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("preparing", "En préparation"),
                            ("ready", "Prête"),
                            ("completed", "Terminée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "producer_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes du producteur (ex: ajustement de poids)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_orders",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous-commande",
                "verbose_name_plural": "Sous-commandes",
                "db_table": "sub_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.IntegerField(
                        help_text="ID du produit (référence à la table products)"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text="Nom du produit au moment de la commande",
                        max_length=255,
                    ),
                ),
                (
                    "quantity_ordered",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantité commandée (unités ou kg)",
                        max_digits=10,
                    ),
                ),
                (
                    "quantity_actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Quantité réelle après préparation (pour produits au poids)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix unitaire au moment de la commande",
                        max_digits=10,
                    ),
                ),
                (
                    "sale_type",
                    models.CharField(
                        choices=[("unit", "Unité"), ("weight", "Poids")],
                        help_text="Type de vente du produit",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sub_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="order.suborder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de commande",
                "verbose_name_plural": "Items de commande",
                "db_table": "order_items",
            },
        ),
        migrations.AddIndex(
            model_name="suborder",
            index=models.Index(
                fields=["producer_id", "-created_at"],
                name="sub_orders_produce_da676c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="suborder",
            index=models.Index(
                fields=["parent_order", "producer_id"],
                name="sub_orders_parent__ee46d6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="suborder",
            index=models.Index(
                fields=["sub_order_number"], name="sub_orders_sub_ord_d091a6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="suborder",
            constraint=models.UniqueConstraint(
                fields=("parent_order", "producer_id"), name="unique_producer_per_order"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["sub_order", "product_id"],
                name="order_items_sub_ord_a935b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["product_id"], name="order_items_product_a53db1_idx"
            ),
        ),
    ]
